// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eisvpukqthnnxmnqkkma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpc3ZwdWtxdGhubnhtbnFra21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMDEwMTIsImV4cCI6MjA1Mzc3NzAxMn0.EDJht263w_U61n2uQHALH0T-68UzmCJM4q0QHIqU43I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);