// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crursymcrsdtigxyfara.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNydXJzeW1jcnNkdGlneHlmYXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5NTA2MzEsImV4cCI6MjA1MzUyNjYzMX0.tj23rnNhBrMvhUKK-eRm4bjMjdkEgLQf-08t7TyplZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);